# Generated by Django 4.0 on 2021-12-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('"can_mark_returned"', 'Set book as returned'),)},
        ),
    ]
