# Generated by Django 4.0 on 2021-12-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ('due_back',), 'permissions': (('"can_mark_returned"', 'Set book as returned'),)},
        ),
    ]
