# Generated by Django 4.0 on 2021-12-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0006_bookinstancerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Select a author for this book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogApp.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Select a language for this book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogApp.language'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Date Format: YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(help_text='Short info about imprint version', max_length=200),
        ),
    ]
